spring:
  application:
    name: product-safety-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.37/yd_wfw?useUnicode=true&characterEncoding=UTF-8
    username: yd_wfw
    password: yd_wfw
server:
  port: 8005

eureka:
  client:
   serviceUrl:
         defaultZone: http://localhost:8001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yidusoft.domain
logging:
   level:
     com:
       yidusoft:
          dao:  debug