spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.37/yd_wfw?useUnicode=true&characterEncoding=UTF-8
    username: yd_wfw
    password: yd_wfw
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      min-idle: 0
      max-wait: -1
    timeout: 0

    #redis
    # Redis服务器地址
    spring.redis.host= localhost
    # Redis服务器连接端口
    spring.redis.port= 6379
    # 连接池中的最大空闲连接
    spring.redis.pool.max-idle= 8
    # 连接池中的最小空闲连接
    spring.redis.pool.min-idle= 0
    # 连接池最大连接数（使用负值表示没有限制）
    spring.redis.pool.max-active= 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    spring.redis.pool.max-wait= -1
    # 连接超时时间（毫秒）
    spring.redis.timeout= 0


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
