server:
    port: 8888
spring:
    application:
      name: config-service
#      使用git配置文件
#    cloud:
#      config:
#        server:
#          git:
#            username: linkbly@163.com
#            uri: https://git.oschina.net/null_262_4469/spring-cloud-config.git
#            password: Ly107951
#        enabled: true
#    profiles:
#      active: git

#使用本地的配置文件
    profiles:
      active: native
    cloud:
     config:
      server:
        native:
          search-locations: classpath:/properties/
eureka:
  client:
   serviceUrl:
         defaultZone: http://localhost:8001/eureka/
 #spring.cloud.config.server.git.uri：配置git仓库地址
 # spring.cloud.config.server.git.searchPaths：配置仓库路径
 #spring.cloud.config.label：配置仓库的分支
 #spring.cloud.config.server.git.username：访问git仓库的用户名
 #spring.cloud.config.server.git.password：访问git仓库的用户密码